export const rootPaths = {
  root: '/',
  pagesRoot: 'pages',
  authRoot: 'authentication',
};

export default {
  signin: `/${rootPaths.authRoot}/sign-in`,
  signup: `/${rootPaths.authRoot}/sign-up`,
  menu: `/menu`,
  addmenuitems: `/addmenuitems`,
  addnewitems: '/addnewitems',
  order: '/order',
  editorder: '/editorder',
  addorder: '/addorder',
  addtableorder: '/addtableorder',
  tableorder: '/tableorder',
  edittableorder: '/edittableorder',
  landingpage: `/welcome`,
  customerpage: `/customerpage`,
  cartpage: `/cartpage`,
  salesreport: '/salesreport',
  itemreport: '/itemreport',
  settingpage: '/settings',
  thankyou: '/thankyou',
  charges: '/charges',
  scanqrcodeagain: '/scanqrcodeagain',
  contactus: '/contactus',
  qrcode: '/qr-code',
  employeesignin: '/employee/signin',
  employee: '/employee',
  addemployee: '/addemployee',
};
